export const teams = {
    "Atlanta": 'atl',
    "Brooklyn": 'bkn',
    "Boston": 'bos',
    "Charlotte": 'cha',
    "Chicago": 'chi',
    "Cleveland": 'cle',
    "Dallas": 'dal',
    "Denver": 'den',
    "Detroit": 'det',
    "Goldenstate": 'gsw',
    "Houston": 'hou',
    "Indiana": 'ind',
    "Los Angeles C": 'lac',
    "Los Angeles L": 'lal',
    "Memphis": 'mem',
    "Miami": 'mia',
    "Milwaukee": 'mil',
    "Minnesota": 'min',
    "New Orleans": 'nop',
    "New York": 'nyk',
    "Oklahoma City": 'okc',
    "Orlando": 'orl',
    "Philadelphia": 'phi',
    "Phoenix": 'phx',
    "Portland": 'por',
    "Sacramento": 'sac',
    "San Antonio": 'sas',
    "Toronto": 'tor',
    "Utah": 'uta',
    "Washington": 'was'
  }